@startuml

class Student {
    - string studentID
    - string fullName
    - string dob
    - int yearEnrolled
    - float entryScore
    - vector<StudyResult> studyResults
    + bool isRegular()*;
    + void input();
    + void output();
    + float getAverageScore(string semester);
}

class RegularStudent {
    + bool isRegular();
    + void output();
}

class PartTimeStudent {
    - string linkedLocation
    + bool isRegular();
    + void output();
    + string getLinkedLocation();
}

class StudyResult {
    + string semesterName;
    + float avgScore;
}

class Faculty {
    - string facultyName
    - vector<unique_ptr<Student>> students
    + void addStudent(unique_ptr<Student> student);
    + int countRegularStudents();
    + Student* getTopEntryScoreStudent();
    + vector<unique_ptr<Student>> getPartTimeStudentsByLocation;
    + void sortStudents();
    + void displayStatistics();
    + void displayStudents();
}

Student <|-- RegularStudent : is-a
Student <|-- PartTimeStudent : is-a
Student o--> StudyResult : has-a
Faculty o--> Student : manages
@enduml
