@startuml
abstract class Student {
    - fullName : string
    - doB : string
    - sex : string
    - phoneNumber : string
    - universityName : string
    - gradeLevel : string
    + void displayInfo();
    + void inputInfo();
    + float calculateScore();
}

class GoodStudent {
    - gpa : float
    - bestRewardName : string
    + void displayInfo();
    + float calculateScore(); 
}

class NormalStudent {
    - englishScore : float
    - entryTestScore : float
    + void displayInfo();
    + float calculateScore(); 
}

Student <|-- GoodStudent : Generalization 
Student <|-- NormalStudent : Generalization 

@enduml
