@startuml

class Employee {
  - ID: int
  - fullName: String
  - birthday: String
  - phone: String
  - email: String
  - Employee_type: int
  - Employee_count: static int
  + Employee()
  + Employee(int, String, String, String, String)
  + virtual void ShowInfo()
  
  + virtual ~Employee()
}

class Experience {
  - level: int
  + Worker()
  + Worker(String, int, String, String, int)
  + void enterInformation() override
  + void displayInformation() override
}

class Fresher {
  - major: String
  + Engineer()
  + Engineer(String, int, String, String, String)
  + void enterInformation() override
  + void displayInformation() override
}

class Intern {
  - job: String
  + Staff()
  + Staff(String, int, String, String, String)
  + void enterInformation() override
  + void displayInformation() override
}

class EmployeeManager {
  - employeeList: vector<Employee*>
  + void addEmployee(Employee*)
  + void searchByName(String)
  + void displayEmployeeList()
}

Employee <|-- Worker
Employee <|-- Engineer
Employee <|-- Staff
EmployeeManager o--> Employee : manages

@enduml
